# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenerateReportsUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(275, 450)
        Dialog.setMinimumSize(QtCore.QSize(275, 450))
        Dialog.setMaximumSize(QtCore.QSize(275, 450))
        Dialog.setModal(True)
        Dialog.setWindowIcon(QtGui.QIcon('AF Logo.png'))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(25, 20, 225, 290))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 30, 211, 260))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxBank = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxBank.setFont(font)
        self.checkBoxBank.setChecked(True)
        self.checkBoxBank.setObjectName("checkBoxBank")
        self.verticalLayout.addWidget(self.checkBoxBank)
        self.checkBoxCash = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxCash.setFont(font)
        self.checkBoxCash.setChecked(True)
        self.checkBoxCash.setObjectName("checkBoxCash")
        self.verticalLayout.addWidget(self.checkBoxCash)
        self.checkBoxCD = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxCD.setFont(font)
        self.checkBoxCD.setChecked(True)
        self.checkBoxCD.setObjectName("checkBoxCD")
        self.verticalLayout.addWidget(self.checkBoxCD)
        self.checkBoxEquity = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxEquity.setFont(font)
        self.checkBoxEquity.setChecked(True)
        self.checkBoxEquity.setObjectName("checkBoxEquity")
        self.verticalLayout.addWidget(self.checkBoxEquity)
        self.checkBoxRetirement = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxRetirement.setFont(font)
        self.checkBoxRetirement.setChecked(True)
        self.checkBoxRetirement.setObjectName("checkBoxRetirement")
        self.verticalLayout.addWidget(self.checkBoxRetirement)
        self.checkBoxTreasury = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxTreasury.setFont(font)
        self.checkBoxTreasury.setChecked(True)
        self.checkBoxTreasury.setObjectName("checkBoxTreasury")
        self.verticalLayout.addWidget(self.checkBoxTreasury)
        self.checkBoxDebt = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxDebt.setFont(font)
        self.checkBoxDebt.setChecked(True)
        self.checkBoxDebt.setObjectName("checkBoxDebt")
        self.verticalLayout.addWidget(self.checkBoxDebt)
        self.checkBoxCredit = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxCredit.setFont(font)
        self.checkBoxCredit.setChecked(True)
        self.checkBoxCredit.setObjectName("checkBoxCredit")
        self.verticalLayout.addWidget(self.checkBoxCredit)
        self.pushButtonSelectAll = QtWidgets.QPushButton(Dialog)
        self.pushButtonSelectAll.setGeometry(QtCore.QRect(35, 320, 98, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonSelectAll.setFont(font)
        self.pushButtonSelectAll.setObjectName("pushButtonSelectAll")
        self.pushButtonPrint = QtWidgets.QPushButton(Dialog)
        self.pushButtonPrint.setGeometry(QtCore.QRect(35, 397, 200, 25))
        self.pushButtonPrint.setObjectName("pushButtonPrint")
        self.pushButtonDeselect = QtWidgets.QPushButton(Dialog)
        self.pushButtonDeselect.setGeometry(QtCore.QRect(138, 320, 98, 25))
        self.pushButtonDeselect.setObjectName("pushButtonDeselect")
        self.lineEditPathway = QtWidgets.QLineEdit(Dialog)
        self.lineEditPathway.setGeometry(QtCore.QRect(35, 370, 171, 21))
        self.lineEditPathway.setObjectName("lineEditPathway")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(35, 350, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonFile = QtWidgets.QPushButton(Dialog)
        self.pushButtonFile.setGeometry(QtCore.QRect(210, 370, 25, 21))
        self.pushButtonFile.setObjectName("pushButtonFile")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Account Types"))
        self.checkBoxBank.setText(_translate("Dialog", "Bank"))
        self.checkBoxCash.setText(_translate("Dialog", "Cash "))
        self.checkBoxCD.setText(_translate("Dialog", "Certificates of Deposit"))
        self.checkBoxEquity.setText(_translate("Dialog", "Equity"))
        self.checkBoxRetirement.setText(_translate("Dialog", "Retirement Accounts"))
        self.checkBoxTreasury.setText(_translate("Dialog", "Treasury Bonds"))
        self.checkBoxDebt.setText(_translate("Dialog", "Debt Accounts"))
        self.checkBoxCredit.setText(_translate("Dialog", "Credit Card Accounts"))
        self.pushButtonSelectAll.setText(_translate("Dialog", "Select All"))
        self.pushButtonPrint.setText(_translate("Dialog", "Generate Report"))
        self.pushButtonDeselect.setText(_translate("Dialog", "Deselect All"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.pushButtonFile.setText(_translate("Dialog", "..."))
